/*
 * This file is part of Campfire.
 * Copyright (c) Pandula Péter 2017-2026.
 * https://github.com/pandulapeter/campfire
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * https://mozilla.org/MPL/2.0/.
 */
package com.pandulapeter.campfire.presentation.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

/**
 * The palettes the app offers besides its own, one per seed color: Material's tonal spot mapping of that seed,
 * which is the same mapping Android derives a wallpaper's colors with, so the "System" option sits among these
 * rather than apart from them.
 *
 * These are data and not design. Every value here is what the seed noted above each pair produces, so a new color
 * is a seed run through Material's tonal mapping rather than forty hand-picked ones, and nothing in here is worth
 * editing on its own - a role that looks wrong is a seed that was chosen wrong.
 *
 * The seeds are spread around the hue circle with the Campfire orange counted as one of them, which is what keeps
 * two of the swatches in the settings screen from reading as the same color.
 */
internal object MaterialColorSchemes {

    /** Seeded with #D32F2F. */
    val Red = ColorSchemePair(
        light = lightColorScheme(
            primary = Color(0xFF904A45),
            onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFFFFDAD6),
            onPrimaryContainer = Color(0xFF73332F),
            inversePrimary = Color(0xFFFFB3AC),
            secondary = Color(0xFF775653),
            onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFFFFDAD6),
            onSecondaryContainer = Color(0xFF5D3F3C),
            tertiary = Color(0xFF725B2E),
            onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFFFEDEA6),
            onTertiaryContainer = Color(0xFF584419),
            background = Color(0xFFFFF8F7),
            onBackground = Color(0xFF231918),
            surface = Color(0xFFFFF8F7),
            onSurface = Color(0xFF231918),
            surfaceVariant = Color(0xFFF5DDDB),
            onSurfaceVariant = Color(0xFF534342),
            surfaceTint = Color(0xFF904A45),
            inverseSurface = Color(0xFF392E2D),
            inverseOnSurface = Color(0xFFFFEDEB),
            error = Color(0xFFBA1A1A),
            onError = Color(0xFFFFFFFF),
            errorContainer = Color(0xFFFFDAD6),
            onErrorContainer = Color(0xFF93000A),
            outline = Color(0xFF857371),
            outlineVariant = Color(0xFFD8C2BF),
            scrim = Color(0xFF000000),
            surfaceBright = Color(0xFFFFF8F7),
            surfaceDim = Color(0xFFE8D6D4),
            surfaceContainerLowest = Color(0xFFFFFFFF),
            surfaceContainerLow = Color(0xFFFFF0EF),
            surfaceContainer = Color(0xFFFCEAE8),
            surfaceContainerHigh = Color(0xFFF6E4E2),
            surfaceContainerHighest = Color(0xFFF1DEDC),
        ),
        dark = darkColorScheme(
            primary = Color(0xFFFFB3AC),
            onPrimary = Color(0xFF571E1A),
            primaryContainer = Color(0xFF73332F),
            onPrimaryContainer = Color(0xFFFFDAD6),
            inversePrimary = Color(0xFF904A45),
            secondary = Color(0xFFE7BDB8),
            onSecondary = Color(0xFF442927),
            secondaryContainer = Color(0xFF5D3F3C),
            onSecondaryContainer = Color(0xFFFFDAD6),
            tertiary = Color(0xFFE1C38C),
            onTertiary = Color(0xFF3F2D04),
            tertiaryContainer = Color(0xFF584419),
            onTertiaryContainer = Color(0xFFFEDEA6),
            background = Color(0xFF1A1110),
            onBackground = Color(0xFFF1DEDC),
            surface = Color(0xFF1A1110),
            onSurface = Color(0xFFF1DEDC),
            surfaceVariant = Color(0xFF534342),
            onSurfaceVariant = Color(0xFFD8C2BF),
            surfaceTint = Color(0xFFFFB3AC),
            inverseSurface = Color(0xFFF1DEDC),
            inverseOnSurface = Color(0xFF392E2D),
            error = Color(0xFFFFB4AB),
            onError = Color(0xFF690005),
            errorContainer = Color(0xFF93000A),
            onErrorContainer = Color(0xFFFFDAD6),
            outline = Color(0xFFA08C8A),
            outlineVariant = Color(0xFF534342),
            scrim = Color(0xFF000000),
            surfaceBright = Color(0xFF423735),
            surfaceDim = Color(0xFF1A1110),
            surfaceContainerLowest = Color(0xFF140C0B),
            surfaceContainerLow = Color(0xFF231918),
            surfaceContainer = Color(0xFF271D1C),
            surfaceContainerHigh = Color(0xFF322826),
            surfaceContainerHighest = Color(0xFF3D3231),
        ),
    )

    /** Seeded with #FBC02D. */
    val Yellow = ColorSchemePair(
        light = lightColorScheme(
            primary = Color(0xFF785A0B),
            onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFFFFDFA0),
            onPrimaryContainer = Color(0xFF5C4300),
            inversePrimary = Color(0xFFEAC16C),
            secondary = Color(0xFF6B5C3F),
            onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFFF5E0BB),
            onSecondaryContainer = Color(0xFF53452A),
            tertiary = Color(0xFF4A6546),
            onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFFCCEBC4),
            onTertiaryContainer = Color(0xFF334D30),
            background = Color(0xFFFFF8F2),
            onBackground = Color(0xFF1F1B13),
            surface = Color(0xFFFFF8F2),
            onSurface = Color(0xFF1F1B13),
            surfaceVariant = Color(0xFFEDE1CF),
            onSurfaceVariant = Color(0xFF4D4639),
            surfaceTint = Color(0xFF785A0B),
            inverseSurface = Color(0xFF353027),
            inverseOnSurface = Color(0xFFFAEFE2),
            error = Color(0xFFBA1A1A),
            onError = Color(0xFFFFFFFF),
            errorContainer = Color(0xFFFFDAD6),
            onErrorContainer = Color(0xFF93000A),
            outline = Color(0xFF7F7667),
            outlineVariant = Color(0xFFD0C5B4),
            scrim = Color(0xFF000000),
            surfaceBright = Color(0xFFFFF8F2),
            surfaceDim = Color(0xFFE2D9CC),
            surfaceContainerLowest = Color(0xFFFFFFFF),
            surfaceContainerLow = Color(0xFFFCF2E5),
            surfaceContainer = Color(0xFFF7ECDF),
            surfaceContainerHigh = Color(0xFFF1E7D9),
            surfaceContainerHighest = Color(0xFFEBE1D4),
        ),
        dark = darkColorScheme(
            primary = Color(0xFFEAC16C),
            onPrimary = Color(0xFF402D00),
            primaryContainer = Color(0xFF5C4300),
            onPrimaryContainer = Color(0xFFFFDFA0),
            inversePrimary = Color(0xFF785A0B),
            secondary = Color(0xFFD8C4A0),
            onSecondary = Color(0xFF3B2F15),
            secondaryContainer = Color(0xFF53452A),
            onSecondaryContainer = Color(0xFFF5E0BB),
            tertiary = Color(0xFFB1CFA9),
            onTertiary = Color(0xFF1D361B),
            tertiaryContainer = Color(0xFF334D30),
            onTertiaryContainer = Color(0xFFCCEBC4),
            background = Color(0xFF17130B),
            onBackground = Color(0xFFEBE1D4),
            surface = Color(0xFF17130B),
            onSurface = Color(0xFFEBE1D4),
            surfaceVariant = Color(0xFF4D4639),
            onSurfaceVariant = Color(0xFFD0C5B4),
            surfaceTint = Color(0xFFEAC16C),
            inverseSurface = Color(0xFFEBE1D4),
            inverseOnSurface = Color(0xFF353027),
            error = Color(0xFFFFB4AB),
            onError = Color(0xFF690005),
            errorContainer = Color(0xFF93000A),
            onErrorContainer = Color(0xFFFFDAD6),
            outline = Color(0xFF998F80),
            outlineVariant = Color(0xFF4D4639),
            scrim = Color(0xFF000000),
            surfaceBright = Color(0xFF3E382F),
            surfaceDim = Color(0xFF17130B),
            surfaceContainerLowest = Color(0xFF110E07),
            surfaceContainerLow = Color(0xFF1F1B13),
            surfaceContainer = Color(0xFF241F17),
            surfaceContainerHigh = Color(0xFF2E2921),
            surfaceContainerHighest = Color(0xFF39342B),
        ),
    )

    /** Seeded with #43A047. */
    val Green = ColorSchemePair(
        light = lightColorScheme(
            primary = Color(0xFF3B6939),
            onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFFBCF0B4),
            onPrimaryContainer = Color(0xFF235024),
            inversePrimary = Color(0xFFA1D39A),
            secondary = Color(0xFF52634F),
            onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFFD5E8CF),
            onSecondaryContainer = Color(0xFF3B4B38),
            tertiary = Color(0xFF38656A),
            onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFFBCEBF0),
            onTertiaryContainer = Color(0xFF1F4D52),
            background = Color(0xFFF7FBF1),
            onBackground = Color(0xFF191D17),
            surface = Color(0xFFF7FBF1),
            onSurface = Color(0xFF191D17),
            surfaceVariant = Color(0xFFDEE5D8),
            onSurfaceVariant = Color(0xFF424940),
            surfaceTint = Color(0xFF3B6939),
            inverseSurface = Color(0xFF2D322C),
            inverseOnSurface = Color(0xFFEFF2E9),
            error = Color(0xFFBA1A1A),
            onError = Color(0xFFFFFFFF),
            errorContainer = Color(0xFFFFDAD6),
            onErrorContainer = Color(0xFF93000A),
            outline = Color(0xFF72796F),
            outlineVariant = Color(0xFFC2C9BD),
            scrim = Color(0xFF000000),
            surfaceBright = Color(0xFFF7FBF1),
            surfaceDim = Color(0xFFD8DBD2),
            surfaceContainerLowest = Color(0xFFFFFFFF),
            surfaceContainerLow = Color(0xFFF1F5EC),
            surfaceContainer = Color(0xFFECEFE6),
            surfaceContainerHigh = Color(0xFFE6E9E0),
            surfaceContainerHighest = Color(0xFFE0E4DB),
        ),
        dark = darkColorScheme(
            primary = Color(0xFFA1D39A),
            onPrimary = Color(0xFF0A390F),
            primaryContainer = Color(0xFF235024),
            onPrimaryContainer = Color(0xFFBCF0B4),
            inversePrimary = Color(0xFF3B6939),
            secondary = Color(0xFFBACCB3),
            onSecondary = Color(0xFF253423),
            secondaryContainer = Color(0xFF3B4B38),
            onSecondaryContainer = Color(0xFFD5E8CF),
            tertiary = Color(0xFFA0CFD4),
            onTertiary = Color(0xFF00363B),
            tertiaryContainer = Color(0xFF1F4D52),
            onTertiaryContainer = Color(0xFFBCEBF0),
            background = Color(0xFF10140F),
            onBackground = Color(0xFFE0E4DB),
            surface = Color(0xFF10140F),
            onSurface = Color(0xFFE0E4DB),
            surfaceVariant = Color(0xFF424940),
            onSurfaceVariant = Color(0xFFC2C9BD),
            surfaceTint = Color(0xFFA1D39A),
            inverseSurface = Color(0xFFE0E4DB),
            inverseOnSurface = Color(0xFF2D322C),
            error = Color(0xFFFFB4AB),
            onError = Color(0xFF690005),
            errorContainer = Color(0xFF93000A),
            onErrorContainer = Color(0xFFFFDAD6),
            outline = Color(0xFF8C9388),
            outlineVariant = Color(0xFF424940),
            scrim = Color(0xFF000000),
            surfaceBright = Color(0xFF363A34),
            surfaceDim = Color(0xFF10140F),
            surfaceContainerLowest = Color(0xFF0B0F0A),
            surfaceContainerLow = Color(0xFF191D17),
            surfaceContainer = Color(0xFF1D211B),
            surfaceContainerHigh = Color(0xFF272B25),
            surfaceContainerHighest = Color(0xFF323630),
        ),
    )

    /** Seeded with #00796B. */
    val Teal = ColorSchemePair(
        light = lightColorScheme(
            primary = Color(0xFF006B5E),
            onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFF9FF2E2),
            onPrimaryContainer = Color(0xFF005047),
            inversePrimary = Color(0xFF83D5C6),
            secondary = Color(0xFF4A635E),
            onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFFCDE8E1),
            onSecondaryContainer = Color(0xFF334B46),
            tertiary = Color(0xFF446179),
            onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFFCAE6FF),
            onTertiaryContainer = Color(0xFF2C4A60),
            background = Color(0xFFF4FBF8),
            onBackground = Color(0xFF171D1B),
            surface = Color(0xFFF4FBF8),
            onSurface = Color(0xFF171D1B),
            surfaceVariant = Color(0xFFDAE5E1),
            onSurfaceVariant = Color(0xFF3F4946),
            surfaceTint = Color(0xFF006B5E),
            inverseSurface = Color(0xFF2B3230),
            inverseOnSurface = Color(0xFFECF2EF),
            error = Color(0xFFBA1A1A),
            onError = Color(0xFFFFFFFF),
            errorContainer = Color(0xFFFFDAD6),
            onErrorContainer = Color(0xFF93000A),
            outline = Color(0xFF6F7976),
            outlineVariant = Color(0xFFBEC9C5),
            scrim = Color(0xFF000000),
            surfaceBright = Color(0xFFF4FBF8),
            surfaceDim = Color(0xFFD5DBD9),
            surfaceContainerLowest = Color(0xFFFFFFFF),
            surfaceContainerLow = Color(0xFFEFF5F2),
            surfaceContainer = Color(0xFFE9EFEC),
            surfaceContainerHigh = Color(0xFFE3EAE7),
            surfaceContainerHighest = Color(0xFFDDE4E1),
        ),
        dark = darkColorScheme(
            primary = Color(0xFF83D5C6),
            onPrimary = Color(0xFF003730),
            primaryContainer = Color(0xFF005047),
            onPrimaryContainer = Color(0xFF9FF2E2),
            inversePrimary = Color(0xFF006B5E),
            secondary = Color(0xFFB1CCC5),
            onSecondary = Color(0xFF1C3530),
            secondaryContainer = Color(0xFF334B46),
            onSecondaryContainer = Color(0xFFCDE8E1),
            tertiary = Color(0xFFACCAE5),
            onTertiary = Color(0xFF133348),
            tertiaryContainer = Color(0xFF2C4A60),
            onTertiaryContainer = Color(0xFFCAE6FF),
            background = Color(0xFF0E1513),
            onBackground = Color(0xFFDDE4E1),
            surface = Color(0xFF0E1513),
            onSurface = Color(0xFFDDE4E1),
            surfaceVariant = Color(0xFF3F4946),
            onSurfaceVariant = Color(0xFFBEC9C5),
            surfaceTint = Color(0xFF83D5C6),
            inverseSurface = Color(0xFFDDE4E1),
            inverseOnSurface = Color(0xFF2B3230),
            error = Color(0xFFFFB4AB),
            onError = Color(0xFF690005),
            errorContainer = Color(0xFF93000A),
            onErrorContainer = Color(0xFFFFDAD6),
            outline = Color(0xFF899390),
            outlineVariant = Color(0xFF3F4946),
            scrim = Color(0xFF000000),
            surfaceBright = Color(0xFF343B39),
            surfaceDim = Color(0xFF0E1513),
            surfaceContainerLowest = Color(0xFF090F0E),
            surfaceContainerLow = Color(0xFF171D1B),
            surfaceContainer = Color(0xFF1B211F),
            surfaceContainerHigh = Color(0xFF252B2A),
            surfaceContainerHighest = Color(0xFF303634),
        ),
    )

    /** Seeded with #1976D2. */
    val Blue = ColorSchemePair(
        light = lightColorScheme(
            primary = Color(0xFF3C6090),
            onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFFD4E3FF),
            onPrimaryContainer = Color(0xFF224876),
            inversePrimary = Color(0xFFA6C8FF),
            secondary = Color(0xFF545F71),
            onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFFD8E3F8),
            onSecondaryContainer = Color(0xFF3D4758),
            tertiary = Color(0xFF6E5676),
            onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFFF7D8FF),
            onTertiaryContainer = Color(0xFF553F5D),
            background = Color(0xFFF9F9FF),
            onBackground = Color(0xFF191C20),
            surface = Color(0xFFF9F9FF),
            onSurface = Color(0xFF191C20),
            surfaceVariant = Color(0xFFE0E2EC),
            onSurfaceVariant = Color(0xFF43474E),
            surfaceTint = Color(0xFF3C6090),
            inverseSurface = Color(0xFF2E3035),
            inverseOnSurface = Color(0xFFF0F0F7),
            error = Color(0xFFBA1A1A),
            onError = Color(0xFFFFFFFF),
            errorContainer = Color(0xFFFFDAD6),
            onErrorContainer = Color(0xFF93000A),
            outline = Color(0xFF74777F),
            outlineVariant = Color(0xFFC3C6CF),
            scrim = Color(0xFF000000),
            surfaceBright = Color(0xFFF9F9FF),
            surfaceDim = Color(0xFFD9DAE0),
            surfaceContainerLowest = Color(0xFFFFFFFF),
            surfaceContainerLow = Color(0xFFF3F3FA),
            surfaceContainer = Color(0xFFEDEDF4),
            surfaceContainerHigh = Color(0xFFE7E8EE),
            surfaceContainerHighest = Color(0xFFE1E2E9),
        ),
        dark = darkColorScheme(
            primary = Color(0xFFA6C8FF),
            onPrimary = Color(0xFF01315E),
            primaryContainer = Color(0xFF224876),
            onPrimaryContainer = Color(0xFFD4E3FF),
            inversePrimary = Color(0xFF3C6090),
            secondary = Color(0xFFBCC7DC),
            onSecondary = Color(0xFF273141),
            secondaryContainer = Color(0xFF3D4758),
            onSecondaryContainer = Color(0xFFD8E3F8),
            tertiary = Color(0xFFDABDE2),
            onTertiary = Color(0xFF3D2846),
            tertiaryContainer = Color(0xFF553F5D),
            onTertiaryContainer = Color(0xFFF7D8FF),
            background = Color(0xFF111318),
            onBackground = Color(0xFFE1E2E9),
            surface = Color(0xFF111318),
            onSurface = Color(0xFFE1E2E9),
            surfaceVariant = Color(0xFF43474E),
            onSurfaceVariant = Color(0xFFC3C6CF),
            surfaceTint = Color(0xFFA6C8FF),
            inverseSurface = Color(0xFFE1E2E9),
            inverseOnSurface = Color(0xFF2E3035),
            error = Color(0xFFFFB4AB),
            onError = Color(0xFF690005),
            errorContainer = Color(0xFF93000A),
            onErrorContainer = Color(0xFFFFDAD6),
            outline = Color(0xFF8D9199),
            outlineVariant = Color(0xFF43474E),
            scrim = Color(0xFF000000),
            surfaceBright = Color(0xFF37393E),
            surfaceDim = Color(0xFF111318),
            surfaceContainerLowest = Color(0xFF0C0E13),
            surfaceContainerLow = Color(0xFF191C20),
            surfaceContainer = Color(0xFF1D2024),
            surfaceContainerHigh = Color(0xFF282A2F),
            surfaceContainerHighest = Color(0xFF32353A),
        ),
    )

    /** Seeded with #7B1FA2. */
    val Purple = ColorSchemePair(
        light = lightColorScheme(
            primary = Color(0xFF765084),
            onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFFF8D8FF),
            onPrimaryContainer = Color(0xFF5D386B),
            inversePrimary = Color(0xFFE4B7F3),
            secondary = Color(0xFF69596D),
            onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFFF1DCF4),
            onSecondaryContainer = Color(0xFF504255),
            tertiary = Color(0xFF815250),
            onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFFFFDAD8),
            onTertiaryContainer = Color(0xFF663B39),
            background = Color(0xFFFFF7FB),
            onBackground = Color(0xFF1F1A1F),
            surface = Color(0xFFFFF7FB),
            onSurface = Color(0xFF1F1A1F),
            surfaceVariant = Color(0xFFEBDFE9),
            onSurfaceVariant = Color(0xFF4C444D),
            surfaceTint = Color(0xFF765084),
            inverseSurface = Color(0xFF342F34),
            inverseOnSurface = Color(0xFFF8EEF5),
            error = Color(0xFFBA1A1A),
            onError = Color(0xFFFFFFFF),
            errorContainer = Color(0xFFFFDAD6),
            onErrorContainer = Color(0xFF93000A),
            outline = Color(0xFF7D747D),
            outlineVariant = Color(0xFFCEC3CD),
            scrim = Color(0xFF000000),
            surfaceBright = Color(0xFFFFF7FB),
            surfaceDim = Color(0xFFE1D7DF),
            surfaceContainerLowest = Color(0xFFFFFFFF),
            surfaceContainerLow = Color(0xFFFBF1F8),
            surfaceContainer = Color(0xFFF5EBF2),
            surfaceContainerHigh = Color(0xFFEFE5ED),
            surfaceContainerHighest = Color(0xFFE9E0E7),
        ),
        dark = darkColorScheme(
            primary = Color(0xFFE4B7F3),
            onPrimary = Color(0xFF442253),
            primaryContainer = Color(0xFF5D386B),
            onPrimaryContainer = Color(0xFFF8D8FF),
            inversePrimary = Color(0xFF765084),
            secondary = Color(0xFFD4C0D7),
            onSecondary = Color(0xFF392C3D),
            secondaryContainer = Color(0xFF504255),
            onSecondaryContainer = Color(0xFFF1DCF4),
            tertiary = Color(0xFFF5B7B5),
            onTertiary = Color(0xFF4C2524),
            tertiaryContainer = Color(0xFF663B39),
            onTertiaryContainer = Color(0xFFFFDAD8),
            background = Color(0xFF161217),
            onBackground = Color(0xFFE9E0E7),
            surface = Color(0xFF161217),
            onSurface = Color(0xFFE9E0E7),
            surfaceVariant = Color(0xFF4C444D),
            onSurfaceVariant = Color(0xFFCEC3CD),
            surfaceTint = Color(0xFFE4B7F3),
            inverseSurface = Color(0xFFE9E0E7),
            inverseOnSurface = Color(0xFF342F34),
            error = Color(0xFFFFB4AB),
            onError = Color(0xFF690005),
            errorContainer = Color(0xFF93000A),
            onErrorContainer = Color(0xFFFFDAD6),
            outline = Color(0xFF978E97),
            outlineVariant = Color(0xFF4C444D),
            scrim = Color(0xFF000000),
            surfaceBright = Color(0xFF3D373D),
            surfaceDim = Color(0xFF161217),
            surfaceContainerLowest = Color(0xFF110D12),
            surfaceContainerLow = Color(0xFF1F1A1F),
            surfaceContainer = Color(0xFF231E23),
            surfaceContainerHigh = Color(0xFF2D282E),
            surfaceContainerHighest = Color(0xFF383339),
        ),
    )

    /** Seeded with #E91EAF. */
    val Pink = ColorSchemePair(
        light = lightColorScheme(
            primary = Color(0xFF874B6D),
            onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFFFFD8EA),
            onPrimaryContainer = Color(0xFF6B3455),
            inversePrimary = Color(0xFFFBB0D8),
            secondary = Color(0xFF715764),
            onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFFFCD9E9),
            onSecondaryContainer = Color(0xFF58404C),
            tertiary = Color(0xFF80543C),
            onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFFFFDBCA),
            onTertiaryContainer = Color(0xFF653D26),
            background = Color(0xFFFFF8F8),
            onBackground = Color(0xFF211A1D),
            surface = Color(0xFFFFF8F8),
            onSurface = Color(0xFF211A1D),
            surfaceVariant = Color(0xFFF0DEE5),
            onSurfaceVariant = Color(0xFF504349),
            surfaceTint = Color(0xFF874B6D),
            inverseSurface = Color(0xFF362E32),
            inverseOnSurface = Color(0xFFFCEDF2),
            error = Color(0xFFBA1A1A),
            onError = Color(0xFFFFFFFF),
            errorContainer = Color(0xFFFFDAD6),
            onErrorContainer = Color(0xFF93000A),
            outline = Color(0xFF827379),
            outlineVariant = Color(0xFFD3C2C9),
            scrim = Color(0xFF000000),
            surfaceBright = Color(0xFFFFF8F8),
            surfaceDim = Color(0xFFE5D6DB),
            surfaceContainerLowest = Color(0xFFFFFFFF),
            surfaceContainerLow = Color(0xFFFFF0F5),
            surfaceContainer = Color(0xFFF9EAEF),
            surfaceContainerHigh = Color(0xFFF3E4E9),
            surfaceContainerHighest = Color(0xFFEDDFE3),
        ),
        dark = darkColorScheme(
            primary = Color(0xFFFBB0D8),
            onPrimary = Color(0xFF511D3E),
            primaryContainer = Color(0xFF6B3455),
            onPrimaryContainer = Color(0xFFFFD8EA),
            inversePrimary = Color(0xFF874B6D),
            secondary = Color(0xFFDFBECD),
            onSecondary = Color(0xFF402A35),
            secondaryContainer = Color(0xFF58404C),
            onSecondaryContainer = Color(0xFFFCD9E9),
            tertiary = Color(0xFFF3BA9C),
            onTertiary = Color(0xFF4A2712),
            tertiaryContainer = Color(0xFF653D26),
            onTertiaryContainer = Color(0xFFFFDBCA),
            background = Color(0xFF181115),
            onBackground = Color(0xFFEDDFE3),
            surface = Color(0xFF181115),
            onSurface = Color(0xFFEDDFE3),
            surfaceVariant = Color(0xFF504349),
            onSurfaceVariant = Color(0xFFD3C2C9),
            surfaceTint = Color(0xFFFBB0D8),
            inverseSurface = Color(0xFFEDDFE3),
            inverseOnSurface = Color(0xFF362E32),
            error = Color(0xFFFFB4AB),
            onError = Color(0xFF690005),
            errorContainer = Color(0xFF93000A),
            onErrorContainer = Color(0xFFFFDAD6),
            outline = Color(0xFF9C8D93),
            outlineVariant = Color(0xFF504349),
            scrim = Color(0xFF000000),
            surfaceBright = Color(0xFF40373B),
            surfaceDim = Color(0xFF181115),
            surfaceContainerLowest = Color(0xFF130C10),
            surfaceContainerLow = Color(0xFF211A1D),
            surfaceContainer = Color(0xFF251E21),
            surfaceContainerHigh = Color(0xFF30282B),
            surfaceContainerHighest = Color(0xFF3B3236),
        ),
    )
}
