[versions]
android-compileSdk = "37" # https://developer.android.com/tools/releases/platforms
android-minSdk = "28"
androidx-activity = "1.13.0" # https://developer.android.com/jetpack/androidx/releases/activity
androidx-appCompat = "1.8.0" # https://developer.android.com/jetpack/androidx/releases/appcompat
androidx-browser = "1.10.0" # https://developer.android.com/jetpack/androidx/releases/browser
androidx-lifecycle = "2.11.0" # https://github.com/JetBrains/compose-multiplatform-core/releases (org.jetbrains.androidx.lifecycle)
androidx-navigation3 = "1.1.1" # https://github.com/JetBrains/compose-multiplatform-core/releases (org.jetbrains.androidx.navigation3)
androidx-room = "2.8.4" # https://developer.android.com/jetpack/androidx/releases/room
androidx-sqlite = "2.7.0" # https://developer.android.com/jetpack/androidx/releases/sqlite
compose-reorderable = "3.1.0" # https://github.com/Calvin-LL/Reorderable/releases
google-material = "1.14.0" # https://github.com/material-components/material-components-android/releases
gradle = "9.4.0" # https://developer.android.com/studio/releases/gradle-plugin
hyperether-localization = "2.0.1" # https://github.com/hyperether/compose-multiplatform-localize/releases
jetbrains-compose = "1.12.0" # https://github.com/JetBrains/compose-jb/releases
jetbrains-compose-material3 = "1.12.0-alpha03" # https://github.com/JetBrains/compose-multiplatform-core/releases (org.jetbrains.compose.material3)
jvmTarget = "21" # https://kotlinlang.org/docs/gradle.html
koin = "4.2.2" # https://github.com/InsertKoinIO/koin/tags
kotlin = "2.4.10" # https://kotlinlang.org/docs/releases.html#release-details
kotlin-coroutines = "1.11.0" # https://github.com/Kotlin/kotlinx.coroutines/releases
kotlin-ksp = "2.3.11" # https://github.com/google/ksp/releases
kotlin-serialization = "1.11.0" # https://github.com/Kotlin/kotlinx.serialization/releases
ktor = "3.5.2" # https://github.com/ktorio/ktor/releases
ktorfit = "2.7.5" # https://github.com/Foso/Ktorfit/releases
theapache64-retrosheet = "3.0.3" # https://github.com/theapache64/retrosheet/releases

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-appCompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appCompat" }
androidx-browser = { module = "androidx.browser:browser", version.ref = "androidx-browser" }
androidx-lifecycle-runtime-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-navigation3-ui = { module = "org.jetbrains.androidx.navigation3:navigation3-ui", version.ref = "androidx-navigation3" }
androidx-room-codegen = { module = "androidx.room:room-compiler", version.ref = "androidx-room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidx-room" }
androidx-sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "androidx-sqlite" }
compose-animation = { module = "org.jetbrains.compose.animation:animation", version.ref = "jetbrains-compose" }
compose-components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "jetbrains-compose" }
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "jetbrains-compose" }
compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "jetbrains-compose-material3" }
compose-reorderable = { module = "sh.calvin.reorderable:reorderable", version.ref = "compose-reorderable" }
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "jetbrains-compose" }
compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "jetbrains-compose" }
google-material = { module = "com.google.android.material:material", version.ref = "google-material" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-core-viewmodel = { module = "io.insert-koin:koin-core-viewmodel", version.ref = "koin" }
kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin-coroutines" }
kotlin-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlin-coroutines" }
kotlin-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlin-serialization" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-contentNegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktorfit = { module = "de.jensklingenberg.ktorfit:ktorfit-lib", version.ref = "ktorfit" }
theapache64-retrosheet = { module = "io.github.theapache64:retrosheet", version.ref = "theapache64-retrosheet" }

[plugins]
android-application = { id = "com.android.application", version.ref = "gradle" }
android-library = { id = "com.android.library", version.ref = "gradle" }
android-multiplatformLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "gradle" }
compose = { id = "org.jetbrains.compose", version.ref = "jetbrains-compose" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
hyperether-localization = { id = "com.hyperether.localization", version.ref = "hyperether-localization" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "kotlin-ksp" }
ktorfit = { id = "de.jensklingenberg.ktorfit", version.ref = "ktorfit" }
