plugins {
    id("campfire-compose-library")
    alias(libs.plugins.hyperether.localization)
}

kotlin {
    sourceSets {
        commonMain {
            // Kotlin string tables generated by the localization plugin from composeResources/values*/strings.xml.
            kotlin.srcDir(layout.buildDirectory.dir("generated/compose/resourceGenerator/kotlin/commonCustomResClass"))
            dependencies {
                implementation(project(":domain:api"))
                implementation(libs.androidx.lifecycle.runtime.compose)
                implementation(libs.androidx.lifecycle.viewmodel.compose)
                implementation(libs.androidx.navigation3.ui)
                implementation(libs.compose.animation)
                implementation(libs.compose.components.resources)
                implementation(libs.compose.foundation)
                implementation(libs.compose.material3)
                implementation(libs.compose.reorderable)
                implementation(libs.compose.runtime)
                implementation(libs.compose.ui)
                implementation(libs.koin.compose)
                implementation(libs.koin.compose.viewmodel)
                implementation(libs.koin.core)
                implementation(libs.koin.core.viewmodel)
                implementation(libs.kotlin.coroutines)
            }
        }
        androidMain.dependencies {
            // Edge-to-edge system bar styling, done by the Android shell in ui/CampfireAndroidApp.kt.
            implementation(libs.androidx.activity.compose)
        }
    }
}

compose.resources {
    publicResClass = false
    packageOfResClass = "com.pandulapeter.campfire.presentation.resources"
    generateResClass = always
}

localization {
    outputPackage.set("com.pandulapeter.campfire.presentation.localization")
}

// The plugin's task only declares the resources folder path as an input, so edited strings.xml files would leave the
// generated string tables stale (and every new string would show up as "???") until a clean build.
tasks.named("generateTranslateFile") {
    inputs.files(fileTree("src/commonMain/composeResources") { include("values*/strings.xml") })
}
