/*
 * This file is part of Campfire.
 * Copyright (c) Pandula Péter 2017-2026.
 * https://github.com/pandulapeter/campfire
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * https://mozilla.org/MPL/2.0/.
 */
plugins {
    id("campfire-compose-library")
    alias(libs.plugins.hyperether.localization)
}

// The app version is declared in gradle.properties; this makes it visible to the shared UI.
val generateVersionFile by tasks.registering {
    val versionName = project.property("campfire.versionName").toString()
    val outputDirectory = layout.buildDirectory.dir("generated/version/kotlin")
    inputs.property("versionName", versionName)
    outputs.dir(outputDirectory)
    doLast {
        outputDirectory.get().asFile.resolve("com/pandulapeter/campfire/presentation").let { directory ->
            directory.mkdirs()
            directory.resolve("CampfireVersion.kt").writeText(
                """
                package com.pandulapeter.campfire.presentation

                internal const val CAMPFIRE_VERSION_NAME = "$versionName"

                """.trimIndent()
            )
        }
    }
}

kotlin {
    sourceSets {
        commonMain {
            // Kotlin string tables generated by the localization plugin from composeResources/values*/strings.xml.
            kotlin.srcDir(layout.buildDirectory.dir("generated/compose/resourceGenerator/kotlin/commonCustomResClass"))
            kotlin.srcDir(generateVersionFile)
            dependencies {
                implementation(project(":domain:api"))
                // The composables render the ChordPro model directly; parsing and transposing go through use cases.
                implementation(project(":chordpro"))
                implementation(libs.androidx.lifecycle.runtime.compose)
                implementation(libs.androidx.lifecycle.viewmodel.compose)
                implementation(libs.androidx.navigation3.ui)
                implementation(libs.compose.animation)
                implementation(libs.compose.components.resources)
                implementation(libs.compose.foundation)
                implementation(libs.compose.material3)
                implementation(libs.compose.reorderable)
                implementation(libs.compose.runtime)
                implementation(libs.compose.ui)
                implementation(libs.koin.compose)
                implementation(libs.koin.compose.viewmodel)
                implementation(libs.koin.core)
                implementation(libs.koin.core.viewmodel)
                implementation(libs.kotlin.coroutines)
            }
        }
        androidMain.dependencies {
            // Edge-to-edge system bar styling, done by the Android shell in ui/CampfireAndroidApp.kt.
            implementation(libs.androidx.activity.compose)
        }
        wasmJsMain.dependencies {
            // Opening URLs in a new tab, done by the web shell in ui/CampfireWebApp.kt.
            implementation(libs.kotlin.browser)
        }
    }
}

compose.resources {
    publicResClass = false
    packageOfResClass = "com.pandulapeter.campfire.presentation.resources"
    generateResClass = always
}

localization {
    outputPackage.set("com.pandulapeter.campfire.presentation.localization")
}

// The plugin's task only declares the resources folder path as an input, so edited strings.xml files would leave the
// generated string tables stale (and every new string would show up as "???") until a clean build.
tasks.named("generateTranslateFile") {
    inputs.files(fileTree("src/commonMain/composeResources") { include("values*/strings.xml") })
}
