plugins {
    id("campfire-compose-library")
    alias(libs.plugins.hyperether.localization)
}

kotlin {
    sourceSets {
        commonMain {
            // Kotlin string tables generated by the localization plugin from composeResources/values*/strings.xml.
            kotlin.srcDir(layout.buildDirectory.dir("generated/compose/resourceGenerator/kotlin/commonCustomResClass"))
            dependencies {
                implementation(project(":domain:api"))
                implementation(libs.androidx.lifecycle.runtime.compose)
                implementation(libs.androidx.lifecycle.viewmodel.compose)
                implementation(libs.androidx.navigation3.ui)
                implementation(libs.compose.animation)
                implementation(libs.compose.components.resources)
                implementation(libs.compose.foundation)
                implementation(libs.compose.material3)
                implementation(libs.compose.reorderable)
                implementation(libs.compose.runtime)
                implementation(libs.compose.ui)
                implementation(libs.koin.compose)
                implementation(libs.koin.compose.viewmodel)
                implementation(libs.koin.core)
                implementation(libs.koin.core.viewmodel)
                implementation(libs.kotlin.coroutines)
            }
        }
    }
}

compose.resources {
    publicResClass = false
    packageOfResClass = "com.pandulapeter.campfire.shared.resources"
    generateResClass = always
}

localization {
    outputPackage.set("com.pandulapeter.campfire.shared.localization")
}
